/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/shosroom.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shosroom.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.717, -0.904, 0.693]} rotation={[-Math.PI / 2, 0, 0]} scale={1.701}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 0.81, 0]}>
            <mesh geometry={nodes.pCube1_Corps_0.geometry} material={materials.Corps} />
            <mesh geometry={nodes.pCube1_lumirere_0.geometry} material={materials.lumirere} />
          </group>
          <group position={[0, 0.81, 0]} rotation={[-Math.PI, 0, 0]} scale={-1}>
            <mesh geometry={nodes.pCube10_Corps_0.geometry} material={materials.Corps} />
            <mesh geometry={nodes.pCube10_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.pCube10_lumirere_0.geometry} material={materials.lumirere} />
          </group>
          <group position={[0, 0.81, 0]}>
            <mesh geometry={nodes.pCube12_Corps_0.geometry} material={materials.Corps} />
            <mesh geometry={nodes.pCube12_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.pCube12_lumirere_0.geometry} material={materials.lumirere} />
          </group>
          <group position={[0, 0.81, 0]} rotation={[-Math.PI, 0, 0]} scale={-1}>
            <mesh geometry={nodes.pCube13_Corps_0.geometry} material={materials.Corps} />
            <mesh geometry={nodes.pCube13_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.pCube13_lumirere_0.geometry} material={materials.lumirere} />
          </group>
          <group position={[0, 0.81, 0]}>
            <mesh geometry={nodes.pCube5_Corps_0.geometry} material={materials.Corps} />
            <mesh geometry={nodes.pCube5_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.pCube5_lumirere_0.geometry} material={materials.lumirere} />
          </group>
          <group rotation={[-Math.PI, 0, 0]} scale={-1}>
            <mesh geometry={nodes.pCube6_Corps_0.geometry} material={materials.Corps} />
            <mesh geometry={nodes.pCube6_lumirere_0.geometry} material={materials.lumirere} />
          </group>
          <group position={[0, 0.81, 0]}>
            <mesh geometry={nodes.pCube8_Corps_0.geometry} material={materials.Corps} />
            <mesh geometry={nodes.pCube8_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.pCube8_lumirere_0.geometry} material={materials.lumirere} />
          </group>
          <group position={[0, 0.81, 0]} rotation={[-Math.PI, 0, 0]} scale={-1}>
            <mesh geometry={nodes.pCube9_Corps_0.geometry} material={materials.Corps} />
            <mesh geometry={nodes.pCube9_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.pCube9_lumirere_0.geometry} material={materials.lumirere} />
          </group>
          <mesh geometry={nodes.pCube11_Corps_0.geometry} material={materials.Corps} />
          <mesh geometry={nodes.pCube11_lumirere_0.geometry} material={materials.lumirere} />
          <mesh geometry={nodes.pCube2_Corps_0.geometry} material={materials['Corps.001']} position={[0, 0.81, 0]} />
          <mesh geometry={nodes.pCylinder1_Inox_0.geometry} material={materials.Inox} position={[0, 0.81, 0]} />
          <mesh geometry={nodes.pPlane1_ecrran_0.geometry} material={materials.ecrran} position={[0, 0.81, 0]} />
          <mesh geometry={nodes.pSphere2_Corps_0.geometry} material={materials.Corps} position={[0, 0.81, 0]} />
        </group>
      </group>
      <group position={[-0.316, -0.478, -0.19]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.689}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0.geometry} material={materials.MAT_Plastic} />
          <mesh geometry={nodes.polySurface2_MAT_Emission_0.geometry} material={materials.MAT_Emission} />
          <mesh geometry={nodes.polySurface4_MAT_Details_0.geometry} material={materials.MAT_Details} />
          <mesh geometry={nodes.polySurface5_MAT_Plastic_0.geometry} material={materials.MAT_Plastic} />
        </group>
      </group>
      <group position={[-0.691, -0.735, 0.694]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group scale={42.327}>
          <mesh geometry={nodes.stem__0.geometry} material={materials['Scene_-_Root']} position={[0, -0.359, 0.299]} />
        </group>
      </group>
      <mesh geometry={nodes.床.geometry} material={materials.グレー床} />
      <mesh geometry={nodes.天板.geometry} material={materials.グレー} position={[-0.35, -0.479, 0.032]} />
      <mesh geometry={nodes.椅子の足.geometry} material={materials['Black rubber']} position={[-0.35, -0.479, 0.032]} />
      <mesh geometry={nodes.くるくる.geometry} material={materials['Black rubber']} position={[-0.512, -0.929, 0.355]} scale={0.023} />
      <mesh geometry={nodes.時計.geometry} material={materials.Blackリニア} position={[-0.993, 0.587, 0.542]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.226, -0.017, -0.227]} />
      <mesh geometry={nodes.部屋001.geometry} material={materials['マテリアル.007']} position={[0.001, 0, 0.001]} />
      <mesh geometry={nodes.中心.geometry} material={materials.木目} position={[0.73, -0.591, -0.597]} rotation={[-0.241, -0.359, -0.086]} scale={[1, 1, 0.326]} />
      <mesh geometry={nodes.左右.geometry} material={materials.木目} position={[0.592, -0.591, -0.65]} rotation={[-0.237, -0.333, -0.197]} scale={[1, 1, 0.326]} />
      <mesh geometry={nodes.支え.geometry} material={materials.木目} position={[0.716, -0.675, -0.562]} rotation={[-0.16, -0.366, 1.513]} scale={[1, 0.652, 0.326]} />
      <mesh geometry={nodes.後ろ支え.geometry} material={materials.木目} position={[0.768, -0.72, -0.695]} rotation={[0.355, -0.445, 0.123]} scale={[0.999, 0.643, 0.315]} />
      <mesh geometry={nodes.キャンバス.geometry} material={materials['04___Default']} position={[0.739, -0.502, -0.606]} rotation={[1.381, -0.076, 0.385]} scale={[0.247, 0.15, 0.15]} />
      <mesh geometry={nodes.椅子マット.geometry} material={materials.椅子緑} position={[0.6, -0.731, -0.265]} rotation={[0, -0.395, 0]} scale={[0.115, 0.03, 0.115]} />
      <mesh geometry={nodes.椅子足001.geometry} material={materials.木目} position={[0.645, -0.842, -0.154]} rotation={[0, -0.395, 0]} scale={[0.024, 0.106, 0.025]} />
      <mesh geometry={nodes.モニター.geometry} material={materials.MAT_Plastic} position={[-0.277, -0.25, 0.032]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.アーム1.geometry} material={materials['Black rubber']} position={[-0.555, -0.284, 0.032]} scale={0.019} />
      <mesh geometry={nodes.アーム2.geometry} material={materials['Black rubber']} position={[-0.555, -0.322, 0.032]} rotation={[0, -0.036, 0]} scale={0.019} />
      <mesh geometry={nodes.アーム3.geometry} material={materials['Black rubber']} position={[-0.594, -0.322, 0.323]} scale={0.019} />
      <mesh geometry={nodes.マウス置き.geometry} material={materials['Black rubber']} position={[-0.316, -0.479, -0.191]} rotation={[0, -1.571, 0]} scale={[-0.074, -0.093, -0.085]} />
      <group position={[0.09, -0.686, 0.019]} scale={1.15}>
        <mesh geometry={nodes.円柱005.geometry} material={materials.グレー} />
        <mesh geometry={nodes.円柱005_1.geometry} material={materials.Blackリニア} />
      </group>
      <mesh geometry={nodes.椅子足.geometry} material={materials.Blackリニア} position={[0.089, -0.873, 0.122]} rotation={[-0.891, 0, 0]} scale={1.15} />
      <mesh geometry={nodes.椅子足2.geometry} material={materials.Blackリニア} position={[-0.008, -0.873, 0.021]} rotation={[-Math.PI / 2, -0.68, -Math.PI / 2]} scale={1.15} />
      <mesh geometry={nodes.Keycaps.geometry} material={materials['Keycap material']} position={[-0.399, -0.492, -0.001]} rotation={[0, 1.571, 0]} scale={0.078} />
      <mesh geometry={nodes.Case.geometry} material={materials['Black rubber']} position={[-0.399, -0.492, -0.001]} rotation={[0, 1.571, 0]} scale={0.078} />
      <mesh geometry={nodes.植木鉢.geometry} material={materials['Black rubber']} position={[-0.684, -0.813, 0.71]} scale={[-0.164, -0.13, -0.164]} />
      <mesh geometry={nodes.土.geometry} material={materials.マテリアル} position={[-0.684, -0.748, 0.71]} scale={[-0.164, -0.13, -0.164]} />
      <mesh geometry={nodes.板.geometry} material={materials.木目} position={[-0.967, -0.337, 0]} />
      <mesh geometry={nodes.平面.geometry} material={materials['Black rubber']} position={[-0.992, -0.346, 0.529]} rotation={[0, 0, -Math.PI / 2]} scale={[0.615, 0.615, 0.404]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.部屋ベース} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials.窓} />
    </group>
  )
}

useGLTF.preload('/shosroom.glb')
